### ISSUE TITLE
Suggestion: allow user to pass icon

### ISSUE THREAD

**Issue by remy** [zachleat/browser-window#3]
Though the code is dependency free, the running version does have a dependency which could/would fail if offline (I'm thinking in html slides and presenting).

It's a great default, but would if the author could provide the URL to their own icon (I'm thinking again an offline URL/localhost).

**Comment by zachleat** [comment]
Shipping with 1.0.5, you can specify any image of your own for the icon with `<img slot="icon">`—thanks!

**Comment by zachleat** [comment]
Demo on https://zachleat.github.io/browser-window/demo.html

**Comment by zachleat** [comment]
(just a note that I flubbed a selector in 1.0.5—use 1.0.6 instead please 😅)
